name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  DOTNET_VERSION: "10.0.x"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore
        run: dotnet restore Swap.slnx

      - name: Build
        run: dotnet build Swap.slnx --configuration Release --no-restore

      - name: Test
        run: dotnet test Swap.slnx --configuration Release --no-build

      - name: Publish
        run: dotnet publish src/Swap.API/Swap.API.csproj --configuration Release --no-build
